# Generated by Django 5.0.4 on 2024-04-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_services', '0003_rename_category_image_service_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='deadline',
            field=models.CharField(max_length=100, verbose_name='срок выполнения'),
        ),
    ]
